# Data Collection

In [42]:
import pandas as pd

In [43]:
df1=pd.read_csv(r'C:\Users\Aishik\Downloads\g1.csv')
df2=pd.read_csv(r'C:\Users\Aishik\Downloads\g2.csv')
df3=pd.read_csv(r'C:\Users\Aishik\Downloads\g3.csv')
Kolkata_DF=pd.read_csv(r'C:\Users\Aishik\Downloads\Kolkata.csv')
s5=pd.read_csv(r'C:\Users\Aishik\Downloads\S5.csv')
durgapur=pd.read_csv(r'C:\Users\Aishik\Downloads\durgapur.csv')
shiliguri=pd.read_csv(r'C:\Users\Aishik\Downloads\Shiliguri.csv')
Kharagpur=pd.read_csv(r'C:\Users\Aishik\Downloads\kharagpur.csv')
haldia=pd.read_csv(r'C:\Users\Aishik\Downloads\haldia.csv')
Hoogly=pd.read_csv(r'C:\Users\Aishik\Downloads\Hoogly.csv')
darjeeling = pd.read_csv(r'C:\Users\Aishik\Downloads\Darjeeling.csv')
Raniganj=pd.read_csv(r'C:\Users\Aishik\Downloads\Raniganj.csv')
Asansol=pd.read_csv(r'C:\Users\Aishik\Downloads\Asansol.csv')
Howrah=pd.read_csv(r'C:\Users\Aishik\Downloads\Howrah.csv')
BidhanNagar=pd.read_csv(r'C:\Users\Aishik\Downloads\BidhanNagar.csv')
Sealdah=pd.read_csv(r'C:\Users\Aishik\Downloads\Sealdah.csv')

In [44]:
Kolkata_DF=pd.concat([df2, df1,df3,Kolkata_DF], ignore_index=True, axis=0)
Kolkata_DF['region']='Kolkata'

In [45]:
s5['region']='Sector V'
durgapur['region']='durgapur'
shiliguri['region']='shiliguri'
Kharagpur['region']='kharagpur'
haldia['region']='haldia'
Hoogly['region']='hoogly'
darjeeling['region']='darjeeling'
Raniganj['region']='Raniganj'
Asansol['region']='Asansol'
Howrah['region']='howrah'
BidhanNagar['region']='bidhannagar'
Sealdah['region']='Sealdah'

In [46]:
final_df=pd.concat([Kolkata_DF,s5,durgapur,shiliguri,Kharagpur,haldia,Hoogly,darjeeling,Raniganj,Asansol,Howrah,BidhanNagar,Sealdah], ignore_index=True, axis=0)

In [47]:
final_df

,OSrXXb,rllt__details,yi40Hd,RDApEe,rllt__details 2,rllt__details 3,yYlJEf href,gqguwf,rllt__details 4,region,BI0Dve,if66xd,BI0Dve 2,aP7g5 src,rnBRZd,ab_button,ab_button href,rllt__details 5
0,V5 Global Kolkata,· District Office,3.4,(44),"5+ years in business · Kolkata, West Bengal",Open ⋅ Closes 7 pm · 070032 66640,https://www.googleadservices.com/pagead/aclk?s...,NaN,NaN,Kolkata,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ManpowerGroup Services India Pvt Ltd. | IT Out...,· Recruiter,4.3,(505),"10+ years in business · Block GP, Plot J-3",Open ⋅ Closes 6:30 pm · 033 4038 1111,http://www.manpowergroup.co.in/,"""... human resource management company in the ...",NaN,Kolkata,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ONE ZONE HR - The best job consultancy | Recru...,· Human resource consulting,4.4,(41),"New Town, West Bengal",Open ⋅ Closes 6:30 pm · 079785 02865,http://onezonehrsolution.com/,NaN,NaN,Kolkata,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Spot Light Career Solutions Pvt. Ltd,· Employment agency,4.8,(16),"Upohar Town Center Chak Garia, near Kavi shuba...",Open ⋅ Closes 6 pm · 099507 26958,http://www.spotlight.careers/,"""... able to hone my skills and able to learn...",NaN,Kolkata,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Jobbaaz Recruitment Solutions,· Recruiter,4.7,(24),"5+ years in business · Room#427, Karnani Mansi...",Open ⋅ Closes 6 pm · 097482 66622,NaN,"""An experienced manpower services provider, wi...",NaN,Kolkata,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1014,Xaviers Consultant (Ascendency Consultant Pvt....,· Employment agency,3.4,(122),"6/11a, KC Ghosh Rd",Open ⋅ Closes 6 pm · 090622 00755,https://www.xaviersconsultant.org/,"""Now a days as a Recruitment Firm they have so...",NaN,Sealdah,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1015,Waytogo Consulting,· Business management consultant,3.9,(11),"14C Apeejay Business Centre 8th Floor, Block B...",NaN,http://jobs.wtgconsultants.in/,NaN,NaN,Sealdah,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1016,Gulf Jobs,· Career guidance service,NaN,NaN,"84, 13, Rafi Ahmed Kidwai Rd",Open ⋅ Closes 9 pm,NaN,NaN,NaN,Sealdah,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1017,HR CONSULTANT,· Business development service,NaN,NaN,"86/7 Brajamani, Brojo Mani Debya Rd",Temporarily closed,NaN,NaN,NaN,Sealdah,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1018,Dmsp Job Consultancy,· Employment consultant,NaN,NaN,"4a, 4, Kasba Rd",Temporarily closed,NaN,NaN,NaN,Sealdah,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
final_df.columns

Index(['OSrXXb', 'rllt__details', 'yi40Hd', 'RDApEe', 'rllt__details 2',
       'rllt__details 3', 'yYlJEf href', 'gqguwf', 'rllt__details 4', 'region',
       'BI0Dve', 'if66xd', 'BI0Dve 2', 'aP7g5 src', 'rnBRZd', 'ab_button',
       'ab_button href', 'rllt__details 5'],
      dtype='object')

In [49]:
final_df.drop(columns=['rllt__details 4',
       'BI0Dve', 'if66xd', 'BI0Dve 2', 'aP7g5 src', 'rnBRZd', 'ab_button',
       'ab_button href', 'rllt__details 5','rllt__details 3'],inplace=True)

In [50]:
final_df

,OSrXXb,rllt__details,yi40Hd,RDApEe,rllt__details 2,yYlJEf href,gqguwf,region
0,V5 Global Kolkata,· District Office,3.4,(44),"5+ years in business · Kolkata, West Bengal",https://www.googleadservices.com/pagead/aclk?s...,NaN,Kolkata
1,ManpowerGroup Services India Pvt Ltd. | IT Out...,· Recruiter,4.3,(505),"10+ years in business · Block GP, Plot J-3",http://www.manpowergroup.co.in/,"""... human resource management company in the ...",Kolkata
2,ONE ZONE HR - The best job consultancy | Recru...,· Human resource consulting,4.4,(41),"New Town, West Bengal",http://onezonehrsolution.com/,NaN,Kolkata
3,Spot Light Career Solutions Pvt. Ltd,· Employment agency,4.8,(16),"Upohar Town Center Chak Garia, near Kavi shuba...",http://www.spotlight.careers/,"""... able to hone my skills and able to learn...",Kolkata
4,Jobbaaz Recruitment Solutions,· Recruiter,4.7,(24),"5+ years in business · Room#427, Karnani Mansi...",NaN,"""An experienced manpower services provider, wi...",Kolkata
...,...,...,...,...,...,...,...,...
1014,Xaviers Consultant (Ascendency Consultant Pvt....,· Employment agency,3.4,(122),"6/11a, KC Ghosh Rd",https://www.xaviersconsultant.org/,"""Now a days as a Recruitment Firm they have so...",Sealdah
1015,Waytogo Consulting,· Business management consultant,3.9,(11),"14C Apeejay Business Centre 8th Floor, Block B...",http://jobs.wtgconsultants.in/,NaN,Sealdah
1016,Gulf Jobs,· Career guidance service,NaN,NaN,"84, 13, Rafi Ahmed Kidwai Rd",NaN,NaN,Sealdah
1017,HR CONSULTANT,· Business development service,NaN,NaN,"86/7 Brajamani, Brojo Mani Debya Rd",NaN,NaN,Sealdah
1018,Dmsp Job Consultancy,· Employment consultant,NaN,NaN,"4a, 4, Kasba Rd",NaN,NaN,Sealdah

In [51]:
final_df.drop(columns=['yYlJEf href', 'gqguwf'],inplace=True)

In [52]:
final_df.drop_duplicates(inplace=True)

DATA Collection Done

# Rename columns names for final analysis also checking Duplicates

In [53]:
final_df.head()

,OSrXXb,rllt__details,yi40Hd,RDApEe,rllt__details 2,region
0,V5 Global Kolkata,· District Office,3.4,(44),"5+ years in business · Kolkata, West Bengal",Kolkata
1,ManpowerGroup Services India Pvt Ltd. | IT Out...,· Recruiter,4.3,(505),"10+ years in business · Block GP, Plot J-3",Kolkata
2,ONE ZONE HR - The best job consultancy | Recru...,· Human resource consulting,4.4,(41),"New Town, West Bengal",Kolkata
3,Spot Light Career Solutions Pvt. Ltd,· Employment agency,4.8,(16),"Upohar Town Center Chak Garia, near Kavi shuba...",Kolkata
4,Jobbaaz Recruitment Solutions,· Recruiter,4.7,(24),"5+ years in business · Room#427, Karnani Mansi...",Kolkata

In [55]:
final_df.columns = ['company_name','company_type','rating_on_google_maps','user_reviews','details','region']

In [38]:
final_df.to_csv(r'D:\Market_research\comp.csv',index=False)

Data preparation and cleaning Done